### PR TITLE
[#66] fixes

### LINKED ISSUE #66: Fixes

### PR DESCRIPTION
**Pull request by lilareliga**
- add put to collection endpoints
- add get to answer history endpoints
- update tests & add deletion of tags after tests
- add link to swagger in readme
- add authorization function from utils to session
- remove unused imports &  unnecessary console.logs
- add missing return types in session engine
- retrieve data of logger user instead of requiring them in req.body
- unified messages and status
- remove model of statistics

### CODE REVIEW

File: server/src/models/FlashcardCollection.ts [hunk 1]
```diff
@@ -59,4 +59,16 @@ function validateFlashcardCollection(flashcardCollection: typeof FlashcardCollec
     return schema.validate(flashcardCollection);
 }
 
-export { FlashcardCollection, IFlashcardCollection, validateFlashcardCollection };
+function validateFlashcardCollectionUpdate(flashcardCollection: typeof FlashcardCollection): Joi.ValidationResult {
```
Comment (Nebrakada) [inline server/src/models/FlashcardCollection.ts]: czy tam nie mozna dać IFlashcardCollection?

**Review by CaptainObjective — APPROVED** [review]
